### ISSUE TITLE
TypeError: 'MolmoProcessor' object is not callable

### ISSUE THREAD

**Issue by wouterdebie** [SeanScripts/ComfyUI-PixtralLlamaVision#7]
I'm using molmo-7B-D-bnb-4bit, since I only have 24 GB of VRAM and I'm getting the following error:

```
Batch of torch.Size([1, 538, 499, 3]) images
!!! Exception during processing !!! 'MolmoProcessor' object is not callable
Traceback (most recent call last):
  File "/home/wouter/comfy/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wouter/comfy/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wouter/comfy/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/wouter/comfy/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wouter/comfy/ComfyUI/custom_nodes/ComfyUI-PixtralLlamaVision/nodes.py", line 133, in generate_text
    inputs = pixtral_model['processor'](images=image_list, text=prompt, return_tensors="pt").to(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MolmoProcessor' object is not callable
```

Any idea?

**Comment by SeanScripts** [comment]
Looks like you're using the Generate Text with Pixtral node. Use the
Generate Text with Molmo node for the Molmo model and it should work
